version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cd manual && mdbook clean
      - cmd: cargo +stable clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov-data:
    desc: Generates code coverage data
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --no-report

  cov:
    desc: Generates code coverage report in text format
    cmds:
      - task: cov-data
      - cmd: cargo +stable llvm-cov report

  cov-html:
    desc: Generates code coverage report in HTML format
    cmds:
      - task: cov-data
      - cmd: cargo +stable llvm-cov --html

  cov-html-open:
    desc: Generates code coverage report in HTML format
    cmds:
      - task: cov-data
      - cmd: cargo +stable llvm-cov --html --open

  cov-badge:
    desc: Generates the detailed code coverage badge
    cmds:
      - task: cov-data
      - cmd: cargo +stable llvm-cov --json --summary-only | coverio -l coverage -c --tag cov-badge

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +nightly fmt

  manual:
    desc: Builds the manual from its markdown files
    cmds:
      - cmd: cd manual && mdbook build

  readme:
    desc: Regenerates README.md file
    cmds:
      - cmd: magg readme docs/README.md
      - task: cov-badge

  serve-manual:
    desc: Serves the manual locally and rebuilds on changes
    ignore_error: true
    cmds:
      - cmd: cd manual && mdbook serve || true

  test:
    desc: Tests in debug mode for all settings
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Tests in debug mode for all settings using nextest
    cmds:
      - cmd: cargo +stable nextest run
